
/* Create Table DDL Commands*/

create table Customers(
customerID int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
firstname varchar(20),
lastname varchar(20),
birthdate date,
moneyspent money,
anniversary date
);

create table Products(
ProductID int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
category varchar(255),
price Money
);


create table Employees(
employeeID int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
firstname varchar(50),
lastname varchar(50),
birthdate date
);

create table Orders(
orderID int GENERATED BY DEFAULT AS IDENTITY PRIMARY key, -- setting primary key constraints
customerID int references Customers(customerID), -- setting foreign key constraints
employeeID int references Employees(employeeID),
productID int references Products(productID),
orderTotal Money,
orderDate Date
);

/* Adding columns using alter command*/

alter table Customers
add column PhNumber Varchar(10);

alter table Employees
add column Address varchar(100);

alter table Orders
add column currentdate date;

alter table Orders
add column currentdate DATE default current_date;

alter table Products
add column ExpDate DATE;

-- Testing query

select * from Customers

select * from Employees

select * from Products

/* Modifying the column length*/

alter table customers
alter column firstname type varchar(100);

/* Add costraints using alter command */

alter table Products
add constraint chk_exp_dt check (ExpDate > current_date);
alter 

---- Data check

select * from products p 


select * from customers


/* Aggregate Functions */

-- Count 

select count(*)
from Products



-- Sum()

select Sum(Price)
from Products

select products.expdate, sum(price) 
from products  
group by products.expdate 


select products.category , sum(price) 
from products  
group by products.category ;


select * from products p 

-- Avg

select * from customers c 

select avg(MoneySpent::numeric)
from Customers

-- min ()

select min(price)
from Products

-- max()

select firstname , max(moneySpent)
from Customers
where firstname = 'Hari'
group by 1
-- having max(moneyspent) > '50000'


having 

-- Group BY

select category, min(Price)
from Products
group by category 

select customerid, firstname, Sum(moneyspent)
from Customers
group by 1,2

-- Handling null

alter table Employees
add column shift varchar(20);

select *
from Employees

-- coalease 

select distinct coalesce (shift, 'Day')
from Employees

-- nullif

select nullif(shift, 'Morning')
from Employees


-- Filter rows with NULL

select *
from Employees
where shift is null 

-- Fiter with not null

select *
from Employees
where shift is not null;

-- Relation ship


-- join

select o.ordertotal, o.productid, e.firstname , e.employeeid, p.expdate, p.price 
from Orders O
join Employees E on o.Employeeid = E.EmployeeID
join products p on p.productid = o.productid 


-- Left join

select o.ordertotal, o.productid, e.firstname , e.employeeid
from Orders O
left join Employees E on o.Employeeid = E.EmployeeID 

-- Right join

select o.ordertotal, o.productid, e.firstname , e.employeeid
from Orders O
Right join Employees E on o.Employeeid = E.EmployeeID 

-- Full join

select o.ordertotal, o.productid, e.firstname , e.employeeid
from Orders O
Full join Employees E on o.Employeeid = E.EmployeeID 

--Inner Join

select o.ordertotal, o.productid, e.firstname , e.employeeid
from Orders O
Inner join Employees E on o.Employeeid = E.EmployeeID 


select o.ordertotal, o.productid, e.firstname , e.employeeid
from Orders O
Inner join Employees E on o.Employeeid = E.EmployeeID 
full join customers C on o.customerid = c.customerid 
right join products p  on o.productid = p.productid and p.productid = 4
where p.productid = 4



select * from business_data_class.Student


join the employees, products, orders, and customers table to extract the data having price greater than 200000;
customer name, product, category, orderdate, order price, employeename, price
