
drop schema business_data_class

create schema business_data_class


---- DDL (Data Defining Language)

create table business_data_class.Student (
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
Student_Name Varchar(50),
Course_ID	Varchar(50), -- references Course(Course_ID),
Age numeric check(Age > 30),
Address Varchar(100),
Ph_number Varchar(10),
College_Name Varchar(100) default 'SkillShikya'
);


drop table course cascade


create table business_data_class.Course (
Course_id Varchar(50),
Cousrse_Name Varchar(50),
Course_Detail Varchar(100),
Courser_Time Varchar(50)
)


--- DML( Data Manipulation Language)
 insert into Students(Student_Name, Course_Id, Age, Address, Ph_number)
 values('Luman', 'BDA001', 31,'Lagankhel', '9876543211')
 
 insert into Students(Student_Name, Course_Id, Age, Address, Ph_number)
 values('uma', 'BDA001', 34,'Patan', '9876543611'),
 
 
 insert into Students(Student_Name, Course_Id, Age, Address, Ph_number)
 values('uma', 'BDA001', 34,'Patan', '9876543611'),
 ('nitesh','DS001', 40, 'Dang', '985642127'),
  ('ritesh','AS001', 53, 'Indrachowk', '984642137'),
   ('jitesh','CS001', 34, 'Baneswor', '985652137'),
    ('Tina','MS001', 39, 'Koteshwor', '985644137')
    
    
     insert into Student(Student_Name, Course_Id, Age, Address, Ph_number)
 values('Luman Awale', 'BDA001', 31,'Lagankhel', '9876543211'),
 ('uma Bista', 'BDA001', 34,'Patan', '9876543611'),
 ('uma Khadka', 'BDA001', 34,'Patan', '9876543611'),
 ('nitesh shrestha','DS001', 40, 'Dang', '985642127'),
  ('ritesh rai','AS001', 53, 'Indrachowk', '984642137'),
   ('jitesh kc','CS001', 34, 'Baneswor', '985652137'),
    ('Tina dc','MS001', 39, 'Koteshwor', '985644137')
    
    
    insert into Course
 values('BDA001', 'Business Data Analytics', '2.5 mths', 'Morning'),
 ('DS001', 'Data Science', ' 3 mths', 'Day'),
 ('AS001', 'Advance Science', '5 mths', 'Evening'),
 ('CS001', 'Computer Science', '6 mths', 'Morning')
  
 
 
 
 --- DQL 
 
 select * from Student
 
 select * from course c 
 
 
--- Student Name, address
 
 select Student_Name, Address
 from students
 
 -- Studnent from Koteshwor
 
 select *
 from students s 
 where address = 'Koteshwor'
 
 -- Student age between 30 to 40
 
 
 -- Function 
 select *
 from students s 
 where age between 30 and 40
 
 select * 
 from student
 where student_name like '___ Bis%'
 
 -- And, Not, OR
 
 select * 
 from student s  
 where s.course_id = 'BDA001' and s.age between 30 and 50
 
 
 select *
 from student s
 where not s.course_id = 'BDA001'
 
  select *
 from student s
 where s.course_id not in ('BDA001')
 
 select *
 from student s
 where not s.course_id = 'BDA001'
 
  select *
 from student s
 where s.course_id != 'BDA001'
 
   select *
 from student s
 where s.course_id <> 'BDA001'
 
 --- Aggregate Function
 
 select avg(age)
 from Student
 
 
 create table business_data_class.Items( 
 ItemCode Varchar(50) primary key,
 ItemName Varchar(100),
 Qty int default 0,
 Price numeric,
 Uom Varchar(50)
 )
 
truncate table business_data_class.items
 
 
 insert into business_data_class.items
 Values('A008','Laptop','20','102000'),
('A002','Laptop','20','400000'),
('A003','Grinder','6','2234'),
('A004','mobile','3','456'),
('A005','AC','7','6798'),
('A006','Remote','8','789')

select * from business_data_class.items

select itemname, Sum(price)
from business_data_class.items
where itemname = 'Fan'
group by itemname  



select  itemname, qty, Sum(price)
from business_data_class.items
where itemname = 'Laptop'
group by itemname , qty 


-- Ordering 

select * 
from business_data_class.items
order by itemname asc

-- Null Handling

select coalesce(uom,'0')
from business_data_class.items



Question

1. create a table name customer with customer_id, name, address, order_id, phone_no.
2. create a table name order with order_id, order_name, order_date, order_detail, Price, Adv_payment.
3. insert the 5 unique and 2 dublicate data in the customer and order table.
4. write a query to selecting all the columns from table
5. write a query to selecting name, orderid and order date from order table.
6. write a query filtering the orders from current date order HINT: date = current_date
7. query to filter customer name ram and address is lalitpur 
8. query to filter address not equals to Bhaktapur.
9. use aggregate function to get sum of total order
10. use aggregate function to get order_date and order-name wise summed price.
11. use order by to order the order name.




 
 
 